<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite1-5</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>716a3f79-1cd4-49d9-a3ff-5d3d00d84511</testSuiteGuid>
   <testCaseLink>
      <guid>b7c2cf5e-fb54-4a85-9210-b18470e6a9c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.1_TC01_LoginSuccess</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99fa5dce-5b0a-4cfd-8521-cdc6aaff0bb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc1d1d9c-8166-4bad-b1dc-d2838108c199</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7187029d-4c06-4535-9129-d81cbcfd2103</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.1_TC02_LoginEmpty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>28c04c7a-e0de-4986-93ce-e67af469f74f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.1_TC03_LoginFail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f57686b9-3e44-4dc7-9544-0028d802e993</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.2_TC01_AddStaff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fe7e2598-400e-4b06-8af6-7eb4c61946d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.2_TC02_DupeStaff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51daa6c4-2672-4ebc-9ade-138fa9c28300</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65dea4c6-e685-4ef4-8be9-cbcdf24ca5fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.2_TC03_NoNameStaff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5e40b6a-518e-48d9-9326-d16657109313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8c49627-d3e7-4b66-a297-fa8eaa0555ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>602e0795-5cbf-4553-af23-103bb71d3855</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.3_TC01_ReadStaff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c063ebb8-4f2d-49eb-b310-67e4112b20c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.3_TC02_SearchID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>417ac5b1-ae48-4809-8830-99daed9f0ac7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f453b158-41a4-418e-ad96-bfbd4d00676e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.4_TC01_UpdateStaff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>13a200da-cffe-4bd8-b244-5f67b29c109b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.4_TC02_ReadUpdateStaff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ba79a8f2-9cd8-4456-850d-e0f2727971c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.5_TC01_DeleteStaff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ba777ada-c410-41b9-b683-ed21ee03815c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestCase_Manual/S1.5_TC02_DeletedStaffBehav</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14b214fd-5aa8-4fa8-9107-41321452a1ce</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
