<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_office-boy</name>
   <tag></tag>
   <elementGuidId>112f9e8a-2753-42c5-83f8-3594c1acbe38</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatable-buttons']/tbody/tr[3]/td[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'office-boy' or . = 'office-boy')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;office-boy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d594dabf-7cf6-4650-abb0-7d57a8e2f23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>office-boy</value>
      <webElementGuid>cad19d0a-22ff-4010-ad7a-1261b5e44515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable-buttons&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[3]</value>
      <webElementGuid>6bc52967-4206-4ff1-9bd1-1d18ee0aa331</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatable-buttons']/tbody/tr[3]/td[3]</value>
      <webElementGuid>06439c59-80ae-470d-bea2-5e48887ca481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zidan'])[1]/following::td[1]</value>
      <webElementGuid>39f29590-b532-435e-9e21-f47bc75b613a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/following::td[3]</value>
      <webElementGuid>8928d7ef-6a68-411e-84ec-6ea468708c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zidan@ams.com'])[1]/preceding::td[1]</value>
      <webElementGuid>f61a19e5-4fb5-4c31-a4d4-58a80174a416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagi'])[2]/preceding::td[2]</value>
      <webElementGuid>37a0ca72-73a5-412c-838a-80dba51926b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='office-boy']/parent::*</value>
      <webElementGuid>a2764e98-e278-4c8a-b0f7-766d133e4e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]</value>
      <webElementGuid>2c7c0f03-0879-4214-b516-95021c8a03d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'office-boy' or . = 'office-boy')]</value>
      <webElementGuid>7e59e32c-c6da-4cf0-ae7f-fa4edaf51c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
