<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_zidan123ams.com</name>
   <tag></tag>
   <elementGuidId>80ed4b94-dfe1-447e-8409-fb987a9a7a0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatable-buttons']/tbody/tr[3]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;zidan123@ams.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>82d7c30a-8c04-447d-a361-c711ef2fc96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>zidan123@ams.com</value>
      <webElementGuid>3328b2f8-29a3-4acd-8047-e7b480e0b9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable-buttons&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[4]</value>
      <webElementGuid>64e3bc72-ace1-454b-8a1f-3aab4de11da8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatable-buttons']/tbody/tr[3]/td[4]</value>
      <webElementGuid>4f9ad84b-4dc0-48eb-bc53-7cf9075f20e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='office-boy'])[1]/following::td[1]</value>
      <webElementGuid>b672614b-73fd-4e07-a057-714e28210c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zidan'])[1]/following::td[2]</value>
      <webElementGuid>00dd7802-8b2e-4ee0-9c14-8553745943ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagi'])[2]/preceding::td[1]</value>
      <webElementGuid>2f1a17ec-187f-4170-ae75-8c64631ae4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[3]/preceding::td[3]</value>
      <webElementGuid>b6fc4930-c783-4be4-b894-8feb419c029c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='zidan123@ams.com']/parent::*</value>
      <webElementGuid>e9667378-d932-401b-b78c-cdd206f6cd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]</value>
      <webElementGuid>6f06ea31-763b-46ac-b169-49f4c40be5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'zidan123@ams.com' or . = 'zidan123@ams.com')]</value>
      <webElementGuid>92177e6d-a524-488b-b395-1a53c06a0249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
