<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View all_rounded-circle</name>
   <tag></tag>
   <elementGuidId>5adf8e77-20f3-40cb-b281-ef392a372f13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/nav/ul/li[5]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;user&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22e17398-15e3-4782-8d4c-f18512b526ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/profile1.jpg</value>
      <webElementGuid>33ce6675-e81d-40e1-ab3e-dbc60ab588a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>627e69db-f8bb-4b5c-8fd4-8b849eb6922d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
      <webElementGuid>00e9a069-051c-4e7f-b7e7-e36c2fd3ce67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;topbar&quot;]/nav[@class=&quot;navbar-custom&quot;]/ul[@class=&quot;navbar-right d-flex list-inline float-right mb-0&quot;]/li[@class=&quot;dropdown notification-list&quot;]/div[@class=&quot;dropdown notification-list nav-pro-img&quot;]/a[@class=&quot;dropdown-toggle nav-link arrow-none waves-effect nav-user&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
      <webElementGuid>f607709d-9937-4532-b4fa-85c9f4fceda2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/nav/ul/li[5]/div/a/img</value>
      <webElementGuid>a1bbb227-e8f5-4527-8430-7315b3e355fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='user']</value>
      <webElementGuid>301bed90-564d-4e0c-b4ea-09cc4d2447cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a/img</value>
      <webElementGuid>f1cf8971-0d58-4db5-9d3a-ae76de12a7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/profile1.jpg' and @alt = 'user']</value>
      <webElementGuid>8d997e26-4eb0-415e-81e0-e93e7d9c5f0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
