<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Biometric Device_slimScrollBar</name>
   <tag></tag>
   <elementGuidId>4e1c30ac-55a7-434b-8ab7-e7cfa2ceaa6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slimScrollDiv.mm-active > div.slimScrollBar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.left > .slimScrollDiv > .slimScrollBar</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7f7b9a8-5400-4b4c-9722-917149494c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slimScrollBar</value>
      <webElementGuid>f3717b13-9913-43bb-8ad0-4cb5c9916bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;left side-menu&quot;]/div[@class=&quot;slimScrollDiv mm-active&quot;]/div[@class=&quot;slimScrollBar&quot;]</value>
      <webElementGuid>5a5587ea-1e80-42b4-9abb-46cc6a0595d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div[2]</value>
      <webElementGuid>d5a3d218-6b5c-47c6-9ac5-56c9c3f31e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>1c95a1cf-1d85-48f3-b775-1be8b114771e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
