<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>welcomeToDashboard</name>
   <tag></tag>
   <elementGuidId>9a07f8a5-ad03-4be7-8753-e587ad024948</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Welcome to Attendance Management System' or . = 'Welcome to Attendance Management System')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.breadcrumb-item.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[3]/div/div/div/div/div/ol/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Welcome to Attendance Management System&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>13316d67-fd75-4cb8-b037-e4d37ba521af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb-item active</value>
      <webElementGuid>efaf7423-4907-41b1-b8f1-6f6bf54733e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to Attendance Management System</value>
      <webElementGuid>27fdf211-d46a-4bc6-a008-85daad423c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;content-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;page-title-box&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-sm-6 text-left&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item active&quot;]</value>
      <webElementGuid>8bbf9682-b70f-434f-820f-072067f13697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div/div/div/ol/li</value>
      <webElementGuid>963032ff-c9a1-453b-91a4-081c8dddb4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::li[1]</value>
      <webElementGuid>984cdb0f-d022-4a07-81b9-9974bf04f747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biometric Device'])[1]/following::li[1]</value>
      <webElementGuid>73542878-422f-486a-a60e-8906fcdb2811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome to Attendance Management System']/parent::*</value>
      <webElementGuid>ec48b761-59f9-45ab-86b2-411a3b39f78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li</value>
      <webElementGuid>9da1ea3d-c3d8-49bc-9655-8a845b3461fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Welcome to Attendance Management System' or . = 'Welcome to Attendance Management System')]</value>
      <webElementGuid>7047522c-9ae4-4fbd-8864-37bbcf8a1e21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
